{ lib, pkgs, ... }:

{
  # Generated from the validated sx1 Arch-to-Nix mapping.
  environment.systemPackages = map (path: lib.attrByPath path null pkgs) [
    [ "tor" ] # tor
    [ "tor-browser" ] # tor-browser
    [ "torctl" ] # torctl
    [ "totem-pl-parser" ] # totem-pl-parser
    [ "traceroute" ] # traceroute
    [ "tree-sitter" ] # tree-sitter
    [ "trevorproxy" ] # trevorproxy
    [ "trevorspray" ] # trevorspray
    [ "triton" ] # triton
    [ "truecrack" ] # truecrack
    [ "trufflehog" ] # trufflehog
    [ "tumbler" ] # tumbler
    [ "uacme" ] # uacme
    [ "ubertooth" ] # ubertooth
    [ "udis86" ] # udis86
    [ "udptunnel" ] # udptunnel
    [ "uefi-firmware-parser" ] # uefi-firmware-parser
    [ "ugrep" ] # ugrep
    [ "umap" ] # umap
    [ "unblob" ] # unblob
    [ "uncover" ] # uncover
    [ "undbx" ] # undbx
    [ "unfurl" ] # unfurl
    [ "unix-privesc-check" ] # unix-privesc-check
    [ "unrar" ] # unrar
    [ "unzip" ] # unzip
    [ "urx" ] # urx
    [ "usbmuxd" ] # usbmuxd
    [ "usbredir" ] # usbredir
    [ "usbrip" ] # usbrip
    [ "usbutils" ] # usbutils
    [ "username-anarchy" ] # username-anarchy
    [ "uthash" ] # uthash
    [ "util-linux" ] # util-linux
    [ "uv" ] # uv
    [ "v2ray-domain-list-community" ] # v2ray-domain-list-community
    [ "v2ray-geoip" ] # v2ray-geoip
    [ "vagrant" ] # vagrant
    [ "vala" ] # vala
    [ "vamp-plugin-sdk" ] # vamp-plugin-sdk
    [ "variety" ] # variety
    [ "vde2" ] # vde2
    [ "villain" ] # villain
    [ "virglrenderer" ] # virglrenderer
    [ "virt-manager" ] # virt-manager
    [ "virt-viewer" ] # virt-viewer
    [ "virt-what" ] # virt-what
    [ "virtiofsd" ] # virtiofsd
    [ "virtualbox" ] # virtualbox
    [ "vivaldi" ] # vivaldi
    [ "vivaldi-ffmpeg-codecs" ] # vivaldi-ffmpeg-codecs
    [ "vivisect" ] # vivisect
    [ "vlc" ] # vlc
    [ "vscodium" ] # vscodium
    [ "vt-cli" ] # vt-cli
    [ "vtk" ] # vtk
    [ "vulnx" ] # vulnx
    [ "vuls" ] # vuls
    [ "warpinator" ] # warpinator
    [ "waybackurls" ] # waybackurls
    [ "waylandpp" ] # waylandpp
    [ "waymore" ] # waymore
    [ "wcc" ] # wcc
    [ "webanalyze" ] # webanalyze
    [ "websploit" ] # websploit
    [ "weevely" ] # weevely
    [ "wfuzz" ] # wfuzz
    [ "wget" ] # wget
    [ "which" ] # which
    [ "whispers" ] # whispers
    [ "whois" ] # whois
    [ "winboat" ] # winboat
    [ "wire-desktop" ] # wire-desktop
    [ "wireless-regdb" ] # wireless-regdb
    [ "wireplumber" ] # wireplumber
    [ "wl-clipboard" ] # wl-clipboard
    [ "wmbusmeters" ] # wmbusmeters
    [ "wqy_zenhei" ] # wqy-zenhei
    [ "wuzz" ] # wuzz
    [ "wxhexeditor" ] # wxhexeditor
    [ "x11vnc" ] # x11vnc
    [ "xapp" ] # xapp
    [ "xapp-symbolic-icons" ] # xapp-symbolic-icons
    [ "xcat" ] # xcat
    [ "xdg-desktop-portal" ] # xdg-desktop-portal
    [ "xdg-desktop-portal-gtk" ] # xdg-desktop-portal-gtk
    [ "xdg-user-dirs" ] # xdg-user-dirs
    [ "xdg-utils" ] # xdg-utils
    [ "xf86-video-amdgpu" ] # xf86-video-amdgpu
    [ "xfburn" ] # xfburn
    [ "xfce4-appfinder" ] # xfce4-appfinder
    [ "xfce4-battery-plugin" ] # xfce4-battery-plugin
    [ "xfce4-clipman-plugin" ] # xfce4-clipman-plugin
    [ "xfce4-cpufreq-plugin" ] # xfce4-cpufreq-plugin
    [ "xfce4-cpugraph-plugin" ] # xfce4-cpugraph-plugin
    [ "xfce4-dict" ] # xfce4-dict
    [ "xfce4-eyes-plugin" ] # xfce4-eyes-plugin
    [ "xfce4-fsguard-plugin" ] # xfce4-fsguard-plugin
    [ "xfce4-genmon-plugin" ] # xfce4-genmon-plugin
    [ "xfce4-mailwatch-plugin" ] # xfce4-mailwatch-plugin
    [ "xfce4-mpc-plugin" ] # xfce4-mpc-plugin
    [ "xfce4-netload-plugin" ] # xfce4-netload-plugin
    [ "xfce4-notes-plugin" ] # xfce4-notes-plugin
    [ "xfce4-notifyd" ] # xfce4-notifyd
    [ "xfce4-panel" ] # xfce4-panel
    [ "xfce4-power-manager" ] # xfce4-power-manager
    [ "xfce4-pulseaudio-plugin" ] # xfce4-pulseaudio-plugin
    [ "xfce4-screensaver" ] # xfce4-screensaver
    [ "xfce4-screenshooter" ] # xfce4-screenshooter
    [ "xfce4-sensors-plugin" ] # xfce4-sensors-plugin
    [ "xfce4-session" ] # xfce4-session
    [ "xfce4-settings" ] # xfce4-settings
    [ "xfce4-systemload-plugin" ] # xfce4-systemload-plugin
    [ "xfce4-taskmanager" ] # xfce4-taskmanager
    [ "xfce4-terminal" ] # xfce4-terminal
    [ "xfce4-time-out-plugin" ] # xfce4-time-out-plugin
    [ "xfce4-timer-plugin" ] # xfce4-timer-plugin
    [ "xfce4-verve-plugin" ] # xfce4-verve-plugin
    [ "xfce4-weather-plugin" ] # xfce4-weather-plugin
    [ "xfce4-whiskermenu-plugin" ] # xfce4-whiskermenu-plugin
    [ "xfce4-xkb-plugin" ] # xfce4-xkb-plugin
    [ "xfconf" ] # xfconf
    [ "xfdesktop" ] # xfdesktop
    [ "xfsprogs" ] # xfsprogs
    [ "xfwm4" ] # xfwm4
    [ "xray" ] # xray
    [ "xsel" ] # xsel
    [ "xsstrike" ] # xsstrike
    [ "xz" ] # xz
    [ "yajl" ] # yajl
    [ "yaml-cpp" ] # yaml-cpp
    [ "yay" ] # yay
    [ "ydotool" ] # ydotool
    [ "yersinia" ] # yersinia
    [ "yt-dlp" ] # yt-dlp
    [ "zdns" ] # zdns
    [ "zeek" ] # zeek
    [ "zenity" ] # zenity
    [ "zgrab2" ] # zgrab2
    [ "zip" ] # zip
    [ "zita-ajbridge" ] # zita-ajbridge
    [ "zita-alsa-pcmi" ] # zita-alsa-pcmi
    [ "zita-resampler" ] # zita-resampler
    [ "zsteg" ] # zsteg
    [ "zulu" ] # zulu
  ];
}
