{ lib, pkgs, ... }:

{
  # Generated from the validated sx1 Arch-to-Nix mapping.
  environment.systemPackages = map (path: lib.attrByPath path null pkgs) [
    [ "flare-floss" ] # flare-floss
    [ "flask-unsign" ] # flask-unsign
    [ "flasm" ] # flasm
    [ "flatpak" ] # flatpak
    [ "fmt" ] # fmt
    [ "folks" ] # folks
    [ "fontforge" ] # fontforge
    [ "foomatic-db" ] # foomatic-db
    [ "foomatic-db-engine" ] # foomatic-db-engine
    [ "foomatic-db-nonfree" ] # foomatic-db-nonfree
    [ "foomatic-db-ppds" ] # foomatic-db-ppds
    [ "fprintd" ] # fprintd
    [ "fractal" ] # fractal
    [ "freecad" ] # freecad
    [ "fscan" ] # fscan
    [ "fscrypt" ] # fscrypt
    [ "fuzzdb" ] # fuzzdb
    [ "fwupd" ] # fwupd
    [ "galleta" ] # galleta
    [ "garcon" ] # garcon
    [ "gau" ] # gau
    [ "gawk" ] # gawk
    [ "gd" ] # gd
    [ "gdbgui" ] # gdbgui
    [ "geary" ] # geary
    [ "gegl" ] # gegl
    [ "geoip" ] # geoip
    [ "getsploit" ] # getsploit
    [ "gettext" ] # gettext
    [ "gf" ] # gf
    [ "gfxstream" ] # gfxstream
    [ "ghauri" ] # ghauri
    [ "ghost" ] # ghost
    [ "ghunt" ] # ghunt
    [ "gimp" ] # gimp
    [ "girsh" ] # girsh
    [ "git-dumper" ] # git-dumper
    [ "git-hound" ] # git-hound
    [ "github-cli" ] # github-cli
    [ "github-desktop" ] # github-desktop
    [ "gitkraken" ] # gitkraken
    [ "gjs" ] # gjs
    [ "glew" ] # glew
    [ "glfw" ] # glfw
    [ "glibc" ] # glibc
    [ "glibmm" ] # glibmm
    [ "glm" ] # glm
    [ "gmic" ] # gmic
    [ "gmime3" ] # gmime3
    [ "gnome-autoar" ] # gnome-autoar
    [ "gnome-boxes" ] # gnome-boxes
    [ "gnome-builder" ] # gnome-builder
    [ "gnome-desktop" ] # gnome-desktop
    [ "gnome-firmware" ] # gnome-firmware
    [ "gnome-online-accounts" ] # gnome-online-accounts
    [ "gnome-software" ] # gnome-software
    [ "go-exploitdb" ] # go-exploitdb
    [ "gom" ] # gom
    [ "gomapenum" ] # gomapenum
    [ "gophish" ] # gophish
    [ "goshs" ] # goshs
    [ "gospider" ] # gospider
    [ "gowitness" ] # gowitness
    [ "gpredict" ] # gpredict
    [ "gr-dect2" ] # gr-dect2
    [ "graphicsmagick" ] # graphicsmagick
    [ "graphinder" ] # graphinder
    [ "graphqlmap" ] # graphqlmap
    [ "graphviz" ] # graphviz
    [ "graphw00f" ] # graphw00f
    [ "grype" ] # grype
    [ "gsd" ] # gsd
    [ "gsl" ] # gsl
    [ "gsound" ] # gsound
    [ "gtk-doc" ] # gtk-doc
    [ "gtk-vnc" ] # gtk-vnc
    [ "gtkmm3" ] # gtkmm3
    [ "gtksourceview4" ] # gtksourceview4
    [ "gtksourceview5" ] # gtksourceview5
    [ "gts" ] # gts
    [ "gutenprint" ] # gutenprint
    [ "guvcview" ] # guvcview
    [ "guymager" ] # guymager
    [ "gzip" ] # gzip
    [ "h2spec" ] # h2spec
    [ "h8mail" ] # h8mail
    [ "haiti" ] # haiti
    [ "hakrawler" ] # hakrawler
    [ "handbrake" ] # handbrake
    [ "hash_extender" ] # hash-extender
    [ "hash-identifier" ] # hash-identifier
    [ "hashdeep" ] # hashdeep
    [ "hashid" ] # hashid
    [ "hashpump" ] # hashpump
    [ "hashrat" ] # hashrat
    [ "hblock" ] # hblock
    [ "hdf5" ] # hdf5
    [ "hekatomb" ] # hekatomb
    [ "holehe" ] # holehe
    [ "honggfuzz" ] # honggfuzz
    [ "hopper" ] # hopper
    [ "hostapd-mana" ] # hostapd-mana
    [ "hotpatch" ] # hotpatch
    [ "htop" ] # htop
    [ "httprobe" ] # httprobe
    [ "hypnotix" ] # hypnotix
    [ "id3lib" ] # id3lib
    [ "imhex" ] # imhex
    [ "inetutils" ] # inetutils
    [ "iniparser" ] # iniparser
    [ "inkscape" ] # inkscape
    [ "intel-compute-runtime" ] # intel-compute-runtime
    [ "intel-graphics-compiler" ] # intel-graphics-compiler
    [ "intel-undervolt" ] # intel-undervolt
    [ "inxi" ] # inxi
    [ "ipp-usb" ] # ipp-usb
    [ "iproute2" ] # iproute2
    [ "ipscan" ] # ipscan
    [ "iptables" ] # iptables
    [ "iputils" ] # iputils
    [ "iwd" ] # iwd
    [ "jack_capture" ] # jack_capture
    [ "jaeles" ] # jaeles
    [ "jamesdsp" ] # jamesdsp
    [ "jefferson" ] # jefferson
    [ "jenkins" ] # jenkins
    [ "jfsutils" ] # jfsutils
    [ "jnetmap" ] # jnetmap
    [ "johnny" ] # johnny
    [ "jsonrpc-glib" ] # jsonrpc-glib
    [ "junkie" ] # junkie
    [ "jwt-hack" ] # jwt-hack
    [ "jwtcat" ] # jwtcat
    [ "kddockwidgets" ] # kddockwidgets
    [ "kdsingleapplication" ] # kdsingleapplication
    [ "keepassxc" ] # keepassxc
    [ "kerbrute" ] # kerbrute
    [ "kexec-tools" ] # kexec-tools
    [ "kicad" ] # kicad
    [ "kid3" ] # kid3
    [ "killerbee" ] # killerbee
    [ "kiterunner" ] # kiterunner
    [ "knock" ] # knock
    [ "kodi" ] # kodi
    [ "kontainer" ] # kontainer-git
    [ "krbjack" ] # krbjack
    [ "krita" ] # krita
    [ "krita-plugin-gmic" ] # krita-plugin-gmic
    [ "kube-hunter" ] # kube-hunter
    [ "laudanum" ] # laudanum
    [ "ldapmonitor" ] # ldapmonitor
    [ "ldeep" ] # ldeep
    [ "lensfun" ] # lensfun
    [ "lhasa" ] # lhasa
    [ "lib2geom" ] # lib2geom
    [ "libabw" ] # libabw
    [ "libadwaita" ] # libadwaita
    [ "libaec" ] # libaec
    [ "libao" ] # libao
    [ "libappindicator" ] # libappindicator
    [ "libatomic_ops" ] # libatomic_ops
    [ "libayatana-appindicator" ] # libayatana-appindicator
    [ "libayatana-indicator" ] # libayatana-indicator
    [ "libbde" ] # libbde
    [ "libburn" ] # libburn
    [ "libcacard" ] # libcacard
    [ "libcddb" ] # libcddb
    [ "libcdio-paranoia" ] # libcdio-paranoia
    [ "libcdr" ] # libcdr
    [ "libcec" ] # libcec
    [ "libcmis" ] # libcmis
    [ "libcue" ] # libcue
    [ "libdatachannel" ] # libdatachannel
    [ "libdex" ] # libdex
    [ "libdvdcss" ] # libdvdcss
    [ "libe-book" ] # libe-book
    [ "libepubgen" ] # libepubgen
    [ "libetonyek" ] # libetonyek
    [ "libetpan" ] # libetpan
    [ "libev" ] # libev
    [ "libexif" ] # libexif
    [ "libexttextcat" ] # libexttextcat
    [ "libfabric" ] # libfabric
    [ "libffado" ] # libffado
    [ "libfilezilla" ] # libfilezilla
    [ "libfprint" ] # libfprint
    [ "libfreehand" ] # libfreehand
    [ "libgccjit" ] # libgccjit
    [ "libgee" ] # libgee
    [ "libgig" ] # libgig
    [ "libgit2-glib" ] # libgit2-glib
    [ "libgnomekbd" ] # libgnomekbd
    [ "libgovirt" ] # libgovirt
    [ "libgphoto2" ] # libgphoto2
    [ "libgpod" ] # libgpod
    [ "libgsf" ] # libgsf
    [ "libhandy" ] # libhandy
    [ "libharu" ] # libharu
    [ "libheif" ] # libheif
    [ "libical" ] # libical
    [ "libid3tag" ] # libid3tag
    [ "libieee1284" ] # libieee1284
    [ "libimagequant" ] # libimagequant
    [ "libisoburn" ] # libisoburn
    [ "libisofs" ] # libisofs
    [ "libixion" ] # libixion
    [ "libkeyfinder" ] # libkeyfinder
    [ "liblangtag" ] # liblangtag
    [ "liblo" ] # liblo
    [ "liblzf" ] # liblzf
    [ "libmad" ] # libmad
    [ "libmediainfo" ] # libmediainfo
    [ "libmicrohttpd" ] # libmicrohttpd
    [ "libmms" ] # libmms
    [ "libmspack" ] # libmspack
    [ "libmspub" ] # libmspub
    [ "libmwaw" ] # libmwaw
    [ "libmypaint" ] # libmypaint
    [ "libnbd" ] # libnbd
    [ "libnet" ] # libnet
    [ "libnfs" ] # libnfs
    [ "libodfgen" ] # libodfgen
    [ "libopusenc" ] # libopusenc
    [ "liborcus" ] # liborcus
    [ "libosinfo" ] # libosinfo
    [ "libotf" ] # libotf
    [ "libp11" ] # libp11
    [ "libpagemaker" ] # libpagemaker
    [ "libpanel" ] # libpanel
    [ "libpeas" ] # libpeas
    [ "libphonenumber" ] # libphonenumber
    [ "libportal" ] # libportal
    [ "libportal-gtk3" ] # libportal-gtk3
    [ "libportal-gtk4" ] # libportal-gtk4
    [ "libpst" ] # libpst
    [ "libpwquality" ] # libpwquality
    [ "libqxp" ] # libqxp
    [ "librecad" ] # librecad
    [ "libreoffice-fresh" ] # libreoffice-fresh
    [ "librest" ] # librest
    [ "librevenge" ] # librevenge
    [ "librewolf" ] # librewolf
    [ "libsbsms" ] # libsbsms
    [ "libshumate" ] # libshumate
    [ "libsidplayfp" ] # libsidplayfp
    [ "libsixel" ] # libsixel
    [ "libslirp" ] # libslirp
    [ "libspelling" ] # libspelling
  ];
}
