{ lib, pkgs, ... }:

{
  # Generated from the validated sx1 Arch-to-Nix mapping.
  environment.systemPackages = map (path: lib.attrByPath path null pkgs) [
    [ "a2jmidid" ] # a2jmidid
    [ "a2ps" ] # a2ps
    [ "aardvark-dns" ] # aardvark-dns
    [ "above" ] # above
    [ "ace" ] # ace
    [ "ad-ldap-enum" ] # ad-ldap-enum
    [ "ad-miner" ] # ad-miner
    [ "ada" ] # ada
    [ "adenum" ] # adenum
    [ "adidnsdump" ] # adidnsdump
    [ "aesfix" ] # aesfix
    [ "aeskeyfind" ] # aeskeyfind
    [ "aespipe" ] # aespipe
    [ "afflib" ] # afflib
    [ "aiodnsbrute" ] # aiodnsbrute
    [ "air" ] # air
    [ "airgeddon" ] # airgeddon
    [ "airspyhf" ] # airspyhf
    [ "alembic" ] # alembic
    [ "alsa-firmware" ] # alsa-firmware
    [ "alsa-plugins" ] # alsa-plugins
    [ "altdns" ] # altdns
    [ "amass" ] # amass
    [ "amber" ] # amber
    [ "amoco" ] # amoco
    [ "androguard" ] # androguard
    [ "ansible" ] # ansible
    [ "apache-users" ] # apache-users
    [ "apachetomcatscanner" ] # apachetomcatscanner
    [ "apkid" ] # apkid
    [ "apkleaks" ] # apkleaks
    [ "aptdec" ] # aptdec
    [ "ardour" ] # ardour
    [ "ares" ] # ares
    [ "argus" ] # argus
    [ "argus-clients" ] # argus-clients
    [ "arj" ] # arj
    [ "ark" ] # ark
    [ "armitage" ] # armitage
    [ "arpoison" ] # arpoison
    [ "asn" ] # asn
    [ "asnmap" ] # asnmap
    [ "assetfinder" ] # assetfinder
    [ "atkmm" ] # atkmm
    [ "atlas" ] # atlas
    [ "aubio" ] # aubio
    [ "audacious" ] # audacious
    [ "audacious-plugins" ] # audacious-plugins
    [ "audacity" ] # audacity
    [ "audiofile" ] # audiofile
    [ "augeas" ] # augeas
    [ "autoconf-archive" ] # autoconf-archive
    [ "autopsy" ] # autopsy
    [ "autorandr" ] # autorandr
    [ "avml" ] # avml
    [ "ayatana-ido" ] # ayatana-ido
    [ "b43-fwcutter" ] # b43-fwcutter
    [ "babl" ] # babl
    [ "badsecrets" ] # badsecrets
    [ "bash-completion" ] # bash-completion
    [ "bazaar" ] # bazaar-git
    [ "bbot" ] # bbot
    [ "bed" ] # bed
    [ "bind" ] # bind
    [ "birdfont" ] # birdfont
    [ "bitwig-studio" ] # bitwig-studio
    [ "bkcrack" ] # bkcrack
    [ "blender" ] # blender
    [ "bluesnarfer" ] # bluesnarfer
    [ "bmc-tools" ] # bmc-tools
    [ "boofuzz" ] # boofuzz
    [ "braa" ] # braa
    [ "brakeman" ] # brakeman
    [ "brave" ] # brave-bin
    [ "bridge-utils" ] # bridge-utils
    [ "bruteforce-luks" ] # bruteforce-luks
    [ "bruteforce-salted-openssl" ] # bruteforce-salted-openssl
    [ "bruteforce-wallet" ] # bruteforce-wallet
    [ "brutespray" ] # brutespray
    [ "brutus" ] # brutus
    [ "bsdiff" ] # bsdiff
    [ "btlejack" ] # btlejack
    [ "btrfs-assistant" ] # btrfs-assistant
    [ "btrfs-progs" ] # btrfs-progs
    [ "bulk_extractor" ] # bulk-extractor
    [ "burpsuite" ] # burpsuite
    [ "bvi" ] # bvi
    [ "bytecode-viewer" ] # bytecode-viewer
    [ "bzip2" ] # bzip2
    [ "cai" ] # cai
    [ "caido-cli" ] # caido-cli
    [ "caido-desktop" ] # caido-desktop
    [ "calf" ] # calf
    [ "cameractrls" ] # cameractrls
    [ "cameradar" ] # cameradar
    [ "can-utils" ] # can-utils
    [ "cansina" ] # cansina
    [ "cantoolz" ] # cantoolz
    [ "capa" ] # capa
    [ "capstone" ] # capstone
    [ "cariddi" ] # cariddi
    [ "catatonit" ] # catatonit
    [ "cdrtools" ] # cdrtools
    [ "celt" ] # celt
    [ "cent" ] # cent
    [ "cero" ] # cero
    [ "certgraph" ] # certgraph
    [ "certi" ] # certi
    [ "certipy" ] # certipy
    [ "certsync" ] # certsync
    [ "cewl" ] # cewl
    [ "cflow" ] # cflow
    [ "chainsaw" ] # chainsaw
    [ "chisel" ] # chisel
    [ "chromium" ] # chromium
    [ "circle-flags" ] # circle-flags
    [ "clair" ] # clair
    [ "clang" ] # clang
    [ "claws-mail" ] # claws-mail
    [ "clazy" ] # clazy
    [ "cloudflare-warp" ] # cloudflare-warp-bin
    [ "cloudlist" ] # cloudlist
    [ "cmark" ] # cmark
    [ "cmatrix" ] # cmatrix
    [ "cmospwd" ] # cmospwd
    [ "cntlm" ] # cntlm
    [ "cockpit" ] # cockpit
    [ "cockpit-machines" ] # cockpit-machines
    [ "codeql" ] # codeql
    [ "coercer" ] # coercer
    [ "colord-gtk" ] # colord-gtk
    [ "commix" ] # commix
    [ "composefs" ] # composefs
    [ "conky" ] # conky
    [ "conmon" ] # conmon
    [ "conpass" ] # conpass
    [ "containerd" ] # containerd
    [ "converseen" ] # converseen
    [ "coreutils" ] # coreutils
    [ "cpptest" ] # cpptest
    [ "crackle" ] # crackle
    [ "cracklib" ] # cracklib
    [ "crackql" ] # crackql
    [ "creds" ] # creds
    [ "criu" ] # criu
    [ "crlfuzz" ] # crlfuzz
    [ "cronie" ] # cronie
    [ "crowbar" ] # crowbar
    [ "crun" ] # crun
    [ "cryptsetup" ] # cryptsetup
    [ "csdr" ] # csdr
    [ "ctags" ] # ctags
    [ "ctypes_sh" ] # ctypes-sh
    [ "cubicsdr" ] # cubicsdr
    [ "cups-pk-helper" ] # cups-pk-helper
    [ "curl-impersonate" ] # curl-impersonate
    [ "cvemap" ] # cvemap
    [ "dalfox" ] # dalfox
    [ "darktable" ] # darktable
    [ "dbd" ] # dbd
    [ "dc3dd" ] # dc3dd
    [ "dcfldd" ] # dcfldd
    [ "ddosify" ] # ddosify
    [ "deluge" ] # deluge
    [ "deluge-gtk" ] # deluge-gtk
    [ "deno" ] # deno
    [ "detect-it-easy" ] # detect-it-easy
    [ "detect-secrets" ] # detect-secrets
    [ "dex2jar" ] # dex2jar
    [ "dhcpig" ] # dhcpig
    [ "dialog" ] # dialog
    [ "digikam" ] # digikam
    [ "dirbuster" ] # dirbuster
    [ "dirstalk" ] # dirstalk
    [ "discord" ] # discord
    [ "dislocker" ] # dislocker
    [ "distrobox" ] # distrobox
    [ "dmg2img" ] # dmg2img
    [ "dmidecode" ] # dmidecode
    [ "dmraid" ] # dmraid
    [ "dns2tcp" ] # dns2tcp
    [ "dnschef" ] # dnschef
    [ "dnsdiag" ] # dnsdiag
    [ "dnsmap" ] # dnsmap
    [ "dnstracer" ] # dnstracer
    [ "dnstwist" ] # dnstwist
    [ "dnsvalidator" ] # dnsvalidator
    [ "dnsx" ] # dnsx
    [ "docbook_xsl" ] # docbook-xsl
    [ "docker-compose" ] # docker-compose
    [ "donpapi" ] # donpapi
    [ "doona" ] # doona
    [ "dorkscout" ] # dorkscout
    [ "dos2unix" ] # dos2unix
    [ "dosfstools" ] # dosfstools
    [ "draco" ] # draco
    [ "dracut" ] # dracut
    [ "droidcam" ] # droidcam
    [ "dtc" ] # dtc
    [ "dublin-traceroute" ] # dublin-traceroute
    [ "dvgrab" ] # dvgrab
    [ "e2fsprogs" ] # e2fsprogs
    [ "easytag" ] # easytag
    [ "edb" ] # edb
    [ "efibootmgr" ] # efibootmgr
    [ "egl-gbm" ] # egl-gbm
    [ "egl-wayland" ] # egl-wayland
    [ "egl-wayland2" ] # egl-wayland2
    [ "egl-x11" ] # egl-x11
    [ "eglexternalplatform" ] # eglexternalplatform
    [ "element-desktop" ] # element-desktop
    [ "element-web" ] # element-web
    [ "ell" ] # ell
    [ "emacs" ] # emacs
    [ "embree" ] # embree
    [ "ent" ] # ent
    [ "entropy" ] # entropy
    [ "enum4linux-ng" ] # enum4linux-ng
    [ "eresi" ] # eresi
    [ "ethtool" ] # ethtool
    [ "evil-winrm" ] # evil-winrm
    [ "evil-winrm-py" ] # evil-winrm-py
    [ "evillimiter" ] # evillimiter
    [ "evolution" ] # evolution
    [ "evolution-data-server" ] # evolution-data-server
    [ "exabgp" ] # exabgp
    [ "exe2hex" ] # exe2hex
    [ "exfatprogs" ] # exfatprogs
    [ "exiflooter" ] # exiflooter
    [ "ext4magic" ] # ext4magic
    [ "eyewitness" ] # eyewitness
    [ "f2fs-tools" ] # f2fs-tools
    [ "facter" ] # facter
    [ "fastfetch" ] # fastfetch
    [ "fatresize" ] # fatresize
    [ "fd" ] # fd
    [ "file" ] # file
    [ "filezilla" ] # filezilla
    [ "findutils" ] # findutils
    [ "firefox" ] # firefox
    [ "firefox_decrypt" ] # firefox-decrypt
    [ "firefox-esr" ] # firefox-esr
    [ "firewalk" ] # firewalk
    [ "firewalld" ] # firewalld
    [ "flare" ] # flare
  ];
}
